version: "3.3"
services:
   db:
      image: postgres
      command: /bin/bash -c "/shell_scripts/configure_docker_postgres.sh && /shell_scripts/start_in_docker.sh"
      volumes:
         - ./src/main/shell:/shell_scripts
         - ./src/main/sql:/sql_scripts
      ports:
         - 5432:5432
